version: '3.7'
services:
  db:
    networks:
      - internal
    image: "postgres:11"
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'qusUt1i9obru4ISTUG2f'
    ports:
      - "5432:5432"
    volumes:
      - ppg_prov_db_data:/var/lib/postgresql/data

  srv:
    networks:
      - internal
    environment:
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'qusUt1i9obru4ISTUG2f'
      DB_HOST: 'db'
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/app/app
      - ./db:/home/app/db
      - ./config/routes.rb:/home/app/config/routes.rb
      - ./config/initializers:/home/app/config/initializers

volumes:
  ppg_prov_db_data:

networks:
  internal:
    driver: 'bridge'